# Portfolio "Portfolio Summary" sheet — org-wide KPIs as Metric,Value rows.
["Metric","Value"],
["Organization", (.metadata.organization // "")],
["Projects", (.metadata.projectCount // 0 | tostring)],
["Report Date", (.metadata.reportDate // "")],
["SonarQube URL", (.metadata.sonarUrl // "")],
["Quality Gates Passed", (.portfolio.totals.gatesPassed // 0 | tostring)],
["Quality Gates Failed", (.portfolio.totals.gatesFailed // 0 | tostring)],
["Quality Gates Other", (.portfolio.totals.gatesOther // 0 | tostring)],
["Total Bugs", (.portfolio.totals.bugs // 0 | tostring)],
["Total Vulnerabilities", (.portfolio.totals.vulnerabilities // 0 | tostring)],
["Total Code Smells", (.portfolio.totals.code_smells // 0 | tostring)],
["Total Issues", (.portfolio.totals.issues.total // 0 | tostring)],
["Blocker Issues", (.portfolio.totals.issues.bySeverity.BLOCKER // 0 | tostring)],
["Critical Issues", (.portfolio.totals.issues.bySeverity.CRITICAL // 0 | tostring)],
["Major Issues", (.portfolio.totals.issues.bySeverity.MAJOR // 0 | tostring)],
["Minor Issues", (.portfolio.totals.issues.bySeverity.MINOR // 0 | tostring)],
["Info Issues", (.portfolio.totals.issues.bySeverity.INFO // 0 | tostring)],
["Total Hotspots", (.portfolio.totals.hotspots.total // 0 | tostring)],
["Hotspots To Review", (.portfolio.totals.hotspots.toReview // 0 | tostring)],
["Hotspots Reviewed", (.portfolio.totals.hotspots.reviewed // 0 | tostring)],
["Lines of Code", (.portfolio.totals.ncloc // 0 | tostring)],
["Technical Debt (min)", (.portfolio.totals.sqale_index // 0 | tostring)],
["Weighted Coverage (%)", ((.portfolio.aggregates.coverage // "N/A") | tostring)],
["Weighted Duplications (%)", ((.portfolio.aggregates.duplicated_lines_density // "N/A") | tostring)]
| @csv
