["Metric","Value"],
["Project Key", (.metadata.projectKey // "N/A")],
["Project Name", (.metadata.projectName // .metadata.projectKey // "N/A")],
["Branch", (.metadata.branch // "main")],
["Report Date", (.metadata.reportDate // "N/A")],
["Last Analysis Date", (.metadata.lastAnalysisDate // "N/A")],
["Analysis ID", (.metadata.analysisId // "N/A")],
["SonarQube URL", (.metadata.sonarUrl // "N/A")],
["Quality Gate Status", (.qualityGate.status // "UNKNOWN")],
(if (.metadata | has("qualityGateName"))
 then ["Quality Gate Name", ((.metadata.qualityGateName // "") | if . == "" then "N/A" else . end)]
 else empty end),
((.metadata.qualityProfiles // [])[] | ["Quality Profile (" + (.languageName // .language // "?") + ")", (.name // "N/A")]),
["Bugs", (.measures.bugs // "0")],
["Vulnerabilities", (.measures.vulnerabilities // "0")],
["Code Smells", (.measures.code_smells // "0")],
["Coverage (%)", (.measures.coverage // "N/A")],
["Duplicated Lines Density (%)", (.measures.duplicated_lines_density // "N/A")],
["Lines of Code", (.measures.ncloc // "0")],
["Technical Debt (min)", (.measures.sqale_index // "0")],
["Debt Ratio (%)", (.measures.sqale_debt_ratio // "N/A")],
["Reliability Rating", (.measures.reliability_rating // "N/A")],
["Security Rating", (.measures.security_rating // "N/A")],
["Maintainability Rating", (.measures.sqale_rating // "N/A")],
["Security Hotspots Reviewed (%)", (.measures.security_hotspots_reviewed // "N/A")],
["Security Review Rating", (.measures.security_review_rating // "N/A")],
["New Bugs", (.measures.new_bugs // "N/A")],
["New Vulnerabilities", (.measures.new_vulnerabilities // "N/A")],
["New Code Smells", (.measures.new_code_smells // "N/A")],
["New Coverage (%)", (.measures.new_coverage // "N/A")],
["New Duplicated Lines Density (%)", (.measures.new_duplicated_lines_density // "N/A")],
["Total Issues", (.issuesSummary.total // 0 | tostring)],
["Hotspots Total", (.hotspotsSummary.total // 0 | tostring)],
["Hotspots To Review", (.hotspotsSummary.toReview // 0 | tostring)],
["Hotspots Reviewed", (.hotspotsSummary.reviewed // 0 | tostring)]
| @csv
